name: Push to Azure DevOps

on:
  push:
    branches:
      - stable  # Ejecuta este workflow en cada push a la rama stable

jobs:
  push-to-azure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "${{ secrets.GIT_USER }}"
        git config --global user.email "${{ secrets.GIT_EMAIL }}"

    - name: Add and Commit changes
      run: |
        git add .
        git commit -m "Actualización automática desde GitHub Actions" || echo "No changes to commit"

    - name: Add remote Azure DevOps repository with token authentication
      run: |
        git remote add origin https://rsz9:${{ secrets.AZURE_DEVOPS_TOKEN }}@dev.azure.com/rsz9/HEAVEN/_git/HEAVEN

    - name: Push code to Azure DevOps
      run: |
        git push -u azure --all
